server:
  port: 8090
  servlet:
    context-path: /shop
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hibernatedb?currentSchema=homework
    username: postgres
    password: Killthem86
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none